[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "froster"
version = "0.0.1"
license = {file = "LICENSE"}
description = "Froster is a user-friendly archiving tool for teams transferring data between high-cost Posix systems and affordable S3-like storage like AWS Glacier."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "duckdb<1.0",
    "textual<0.60",
    "requests<2.40",
    "boto3<1.40",
    "psutil<6.0",
    "visidata",
    "inquirer"
]

[project.scripts]
froster = "froster.froster:main"

[project.urls]
"Repository" = "https://github.com/dirkpetersen/froster"