name: froster-config
run-name: Test "froster config" command
on: [push, pull_request]
env:
  REPO: ${{ github.repository }}

jobs:
  check-froster-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install froster
        run: ./install.sh
      - name: Check froster version
        run: froster --version
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Generate dummy files
        run: python3 tests/generate_dummy_files.py
      - name: Run unittests
        run: python3 -m unittest -v