name: froster-config
run-name: Test "froster config" command
on: [push, pull_request]

jobs:
  check-froster-installation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: echo $REPO
      - run: echo $BRANCH
      - run: echo $REPONAME
      - name: Install froster
        run: ./install.sh
      - name: Check froster version
        run: froster --version
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Generate dummy files
        run: python3 tests/generate_dummy_files.py
      - name: Run unittests
        run: python3 -m unittest -v