name: test-github-actions
run-name: Froster installs correctly in Ubuntu-latest
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl --version

