name: froster-config
run-name: Test "froster config" command
on: [push, pull_request]

env:
  REPO: ${{ github.repository }}
  BRANCH: ${{ github.ref }}

jobs:
  check-froster-installation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install froster
        run: ./install.sh

      - name: Check froster version
        run: froster --version

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run unittests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
        run: python3 -m unittest -v
