name: Test "froster config" command

run-name: Test "froster config" command

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  install-froster:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install froster locally (push)
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        env:
          LOCAL_INSTALL: true
        run: ./install.sh

      - name: Install froster via PyPi repository (release)
        if: github.event_name == 'release'
        run: |
          sleep 300
          curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/install.sh?$(date +%s) | bash

      - name: Print froster version
        run: froster --version

      # - name: Run unittests
      #   env:
      #     AWS_ACCESS_KEY_ID: $ {{ secrets.AWS_ACCESS_KEY_ID }}     <--- Delete space of $'s
      #     AWS_SECRET: $ {{ secrets.AWS_SECRET }}     <--- Delete space of $'s
      #   run: python3 -m unittest -v
