name: froster-ubuntu-install
run-name: Check that froster installs correctly in Ubuntu-latest
on: [push, pull_request]
jobs:
  check-froster-installation:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Run install.sh
        run: |
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          ./install.sh
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
      - name: Check froster version
        run: froster --version


