name: Install Froster locally
run-name: Froster local install succeeded on Ubuntu-latest.
on: [push, pull_request]
env:
  REPO: ${{ github.repository }}
  BRANCH: ${{ github.ref }}

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      LOCAL_INSTALL: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install pipx
      run: |
        python -m pip install pipx

    - name: Install froster locally
      run: ./install.sh

    - name: Source ~/.bashrc
      run: source ~/.bashrc

    - name: Check Froster is installed
      run: froster --version

