name: froster-test-generate-dummy-files
run-name: Generate dummy files for testing
on: [push, pull_request]
jobs:
  check-froster-installation:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - run: ./install.sh
      - run: froster --version
      - run: ls -la 
      - run: ls -la froster
      - run: ls -la froster/test
      - run: python3 froster/test/generate_dummy_files.py