name: Test "froster credentials" command

run-name: Test "froster credentials" command

on: [push, pull_request]

jobs:
  froster-index:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install froster locally
        env:
          LOCAL_INSTALL: true
        run: ./install.sh

      - name: Run test_credentials tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
        run: python3 tests/test_credentials.py
